{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "The `__module__` attribute of objects should match the `__name__` of the module they're defined in. The following minimal example fails to maintain that invariant.\r\n\r\n# Steps to reproduce\r\n\r\n## `cytest/__init__.pyx`:\r\n```cython\r\nclass C: pass\r\n```\r\n\r\n## `pyproject.toml`:\r\n```toml\r\n[build-system]\r\nrequires = [\"setuptools\", \"wheel\", \"cython >= 3.0a\"]\r\nbuild-backend = \"setuptools.build_meta\"\r\n```\r\n\r\n## `setup.py`\r\nRemoving `.*` below fixes the problem but creates a different problem if there were more Cython modules under `cytest/`.\r\n```python\r\nfrom setuptools import setup, Extension\r\nfrom Cython.Build import cythonize\r\nsetup(\r\n\tname='cytest',\r\n\text_modules=cythonize([Extension(\"cytest.*\", [\"cytest/*.pyx\"])]))\r\n```\r\n## Compilation and installation\r\nOutput omitted below.\r\n\r\n```console\r\n$ pip install .\r\n$ pip list\r\nPackage    Version\r\n---------- -------\r\ncytest     0.0.0\r\npip        20.2.3\r\nsetuptools 50.3.0\r\n```\r\n\r\n## Actual output\r\n```console\r\n$ python -c'import cytest; print(cytest.C.__module__, cytest.__name__)'                    \r\ncytest.__init__ cytest\r\n```\r\n\r\n# Expected output\r\n```console\r\n$ python -c'import cytest; print(cytest.C.__module__, cytest.__name__)'                    \r\ncytest cytest\r\n```\r\n\r\n# Environment\r\nmacOS 10.15, Python 3.7 and 3.8, Cython 3.0 alpha 6 (as set by `pyproject.toml` above)\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "I meet the same issue, any updates?",
            "created_at": "2021-09-24T03:50:44Z",
            "html_url": "https://github.com/cython/cython/issues/3867#issuecomment-926321152",
            "id": 926321152,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3867",
            "node_id": "IC_kwDOABDGAc43NooA",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/926321152/reactions"
            },
            "updated_at": "2021-09-24T03:50:44Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/926321152",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/37610161?v=4",
                "events_url": "https://api.github.com/users/furoxr/events{/privacy}",
                "followers_url": "https://api.github.com/users/furoxr/followers",
                "following_url": "https://api.github.com/users/furoxr/following{/other_user}",
                "gists_url": "https://api.github.com/users/furoxr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/furoxr",
                "id": 37610161,
                "login": "furoxr",
                "node_id": "MDQ6VXNlcjM3NjEwMTYx",
                "organizations_url": "https://api.github.com/users/furoxr/orgs",
                "received_events_url": "https://api.github.com/users/furoxr/received_events",
                "repos_url": "https://api.github.com/users/furoxr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/furoxr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/furoxr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/furoxr"
            }
        },
        {
            "author_association": "NONE",
            "body": "Same here. Cython 0.29.32, Windows Python 3.10\r\nI defined a class in moule using\r\n```python\r\nclass A():\r\n  pass\r\n```\r\n`A.__module__` is set on compile time.\r\nIf I inserted `__module__ = __name__` to first line of the class, the `__module__` works good like CPython.\r\n```python\r\nclass A():\r\n  __module__ = __name__\r\n  pass\r\n```\r\n\r\nAnother issue is on my end __init__.py could not currectly compiled.",
            "created_at": "2022-09-15T08:49:07Z",
            "html_url": "https://github.com/cython/cython/issues/3867#issuecomment-1247788700",
            "id": 1247788700,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3867",
            "node_id": "IC_kwDOABDGAc5KX76c",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1247788700/reactions"
            },
            "updated_at": "2022-09-19T06:47:56Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1247788700",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1490719?v=4",
                "events_url": "https://api.github.com/users/fanthos/events{/privacy}",
                "followers_url": "https://api.github.com/users/fanthos/followers",
                "following_url": "https://api.github.com/users/fanthos/following{/other_user}",
                "gists_url": "https://api.github.com/users/fanthos/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fanthos",
                "id": 1490719,
                "login": "fanthos",
                "node_id": "MDQ6VXNlcjE0OTA3MTk=",
                "organizations_url": "https://api.github.com/users/fanthos/orgs",
                "received_events_url": "https://api.github.com/users/fanthos/received_events",
                "repos_url": "https://api.github.com/users/fanthos/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fanthos/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fanthos/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fanthos"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Another issue is on my end `__init__.py` could not currectly compiled \r\n\r\nthis is a Windows setuptools/distutils bug I believe.\r\n\r\ndistutils tries to add a compiler flag to force the module init function to be public. Unfortunately it gets the name of the function wrong and so it doesn't link. I believe this is \"fixed\" on Cython 3 by defining a dummy function with the name that setuptools/distutils expects.",
            "created_at": "2022-09-15T18:18:26Z",
            "html_url": "https://github.com/cython/cython/issues/3867#issuecomment-1248444153",
            "id": 1248444153,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3867",
            "node_id": "IC_kwDOABDGAc5Kab75",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1248444153/reactions"
            },
            "updated_at": "2022-09-15T21:02:20Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1248444153",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "But in general a PR would be welcome for this bug - it's almost certainly pretty simple",
            "created_at": "2022-09-15T18:20:11Z",
            "html_url": "https://github.com/cython/cython/issues/3867#issuecomment-1248445665",
            "id": 1248445665,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3867",
            "node_id": "IC_kwDOABDGAc5KacTh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1248445665/reactions"
            },
            "updated_at": "2022-09-15T18:20:11Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1248445665",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "I am using Cython to compile Odoo module and load code using `odoo.addon.modulename` dynamicly, so `__module__` shoule be `odoo.addon.modulename` instead of hardcoded `modulename`.\r\nSeems that `cls.__module__` should assigned runtime but not compile time.\r\n`__module__ = __name__` could be a workaround for the issue.",
            "created_at": "2022-09-16T03:28:42Z",
            "html_url": "https://github.com/cython/cython/issues/3867#issuecomment-1248878232",
            "id": 1248878232,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3867",
            "node_id": "IC_kwDOABDGAc5KcF6Y",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1248878232/reactions"
            },
            "updated_at": "2022-09-16T03:28:42Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1248878232",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1490719?v=4",
                "events_url": "https://api.github.com/users/fanthos/events{/privacy}",
                "followers_url": "https://api.github.com/users/fanthos/followers",
                "following_url": "https://api.github.com/users/fanthos/following{/other_user}",
                "gists_url": "https://api.github.com/users/fanthos/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fanthos",
                "id": 1490719,
                "login": "fanthos",
                "node_id": "MDQ6VXNlcjE0OTA3MTk=",
                "organizations_url": "https://api.github.com/users/fanthos/orgs",
                "received_events_url": "https://api.github.com/users/fanthos/received_events",
                "repos_url": "https://api.github.com/users/fanthos/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fanthos/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fanthos/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fanthos"
            }
        },
        {
            "author_association": "NONE",
            "body": "I workaround the issue at parse phase, by insert `AssignNode(lhs='__module__', rhs='__name__')` to class body. My implement is a dirty fix, and should not be the actual fix for the issue.\r\n\r\nI only fixed Python `class` generation but not check function or other generation, so not sure function or other things effect by the issue or not.",
            "created_at": "2022-09-20T02:37:00Z",
            "html_url": "https://github.com/cython/cython/issues/3867#issuecomment-1251765292",
            "id": 1251765292,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3867",
            "node_id": "IC_kwDOABDGAc5KnGws",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1251765292/reactions"
            },
            "updated_at": "2022-09-20T02:37:17Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1251765292",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1490719?v=4",
                "events_url": "https://api.github.com/users/fanthos/events{/privacy}",
                "followers_url": "https://api.github.com/users/fanthos/followers",
                "following_url": "https://api.github.com/users/fanthos/following{/other_user}",
                "gists_url": "https://api.github.com/users/fanthos/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/fanthos",
                "id": 1490719,
                "login": "fanthos",
                "node_id": "MDQ6VXNlcjE0OTA3MTk=",
                "organizations_url": "https://api.github.com/users/fanthos/orgs",
                "received_events_url": "https://api.github.com/users/fanthos/received_events",
                "repos_url": "https://api.github.com/users/fanthos/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/fanthos/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/fanthos/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/fanthos"
            }
        }
    ],
    "comments": 6,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/3867/comments",
    "created_at": "2020-10-06T18:55:01Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/3867/events",
    "html_url": "https://github.com/cython/cython/issues/3867",
    "id": 715940904,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/3867/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU3MTU5NDA5MDQ=",
    "number": 3867,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 2,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 2,
        "url": "https://api.github.com/repos/cython/cython/issues/3867/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/3867/timeline",
    "title": "[BUG] Objects' __module__ incorrect in some __init__.pyx layouts",
    "updated_at": "2022-09-20T02:37:17Z",
    "url": "https://api.github.com/repos/cython/cython/issues/3867",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1417749?v=4",
        "events_url": "https://api.github.com/users/wkschwartz/events{/privacy}",
        "followers_url": "https://api.github.com/users/wkschwartz/followers",
        "following_url": "https://api.github.com/users/wkschwartz/following{/other_user}",
        "gists_url": "https://api.github.com/users/wkschwartz/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/wkschwartz",
        "id": 1417749,
        "login": "wkschwartz",
        "node_id": "MDQ6VXNlcjE0MTc3NDk=",
        "organizations_url": "https://api.github.com/users/wkschwartz/orgs",
        "received_events_url": "https://api.github.com/users/wkschwartz/received_events",
        "repos_url": "https://api.github.com/users/wkschwartz/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/wkschwartz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wkschwartz/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/wkschwartz"
    }
}