{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "**Describe the bug**\r\nRunning `cy list` against a breakpoint pointing to a function that was defined into a `.pxi` files leads to an empty (or even wrong) source code\r\n\r\n**To Reproduce**\r\nThe pyarrow project has a module `lib.pyx` that is defined as a series of included `.pxi` files\r\n```\r\n...\r\n# DataType, Field, Schema\r\ninclude \"types.pxi\"\r\n\r\n# Array scalar values\r\ninclude \"scalar.pxi\"\r\n\r\n# Array types\r\ninclude \"array.pxi\"\r\n...\r\n```\r\nIf I set a debug point to the `pyarrow.lib.Array.to_numpy` method which is declared in the `array.pxi` source file (as the whole `Array` class is there) then `cygdb`  is unable to understand what's the source code\r\n```\r\n(gdb) cy break pyarrow.lib.Array.to_numpy\r\nFunction \"__pyx_pw_7pyarrow_3lib_5Array_62to_numpy\" not defined.\r\nBreakpoint 1 (__pyx_pw_7pyarrow_3lib_5Array_62to_numpy) pending.\r\n(gdb) cy run\r\n Thread 2 hit Breakpoint 1, 0x000000010681f214 in __pyx_pf_7pyarrow_3lib_5Array_61to_numpy(__pyx_obj_7pyarrow_3lib_Array*, _object*, _object*) () from /Users/amol/arrow/python/pyarrow/lib.cpython-39d-darwin.so\r\n[New Thread 0x2703 of process 81180]\r\n[New Thread 0x2503 of process 81180]\r\n(gdb) cy list\r\n(gdb) cy list\r\nTraceback (most recent call last):\r\n  File \"/home/amol/arrow/cython/Cython/Debugger/libpython.py\", line 1980, in wrapper\r\n    return function(*args, **kwargs)\r\n  File \"/home/amol/arrow/cython/Cython/Debugger/libcython.py\", line 1097, in invoke\r\n    source = sd.get_source(lineno - 5, lineno + 5, mark_line=lineno,\r\n  File \"/home/amol/arrow/cython/Cython/Debugger/libcython.py\", line 83, in wrapper\r\n    return function(self, frame, *args, **kwargs)\r\n  File \"/home/amol/arrow/cython/Cython/Debugger/libcython.py\", line 243, in get_source_desc\r\n    lineno = filename_and_lineno[1]\r\nAssertionError\r\nPython Exception <type 'exceptions.AssertionError'> : \r\nError occurred in Python.\r\n```\r\n\r\nThe problem seems to occur because `get_source_desc` ( https://github.com/cython/cython/blob/efdf996dced075682d86b7e53a12b56b5ebfea38/Cython/Debugger/libcython.py#L237 ) si comparing that the filename of the module where the function was compiled to matches with the filename where the function was declared. In case of `.pxi`  this is obviously not true as the function is declared in one place and is then injected into another one.\r\n\r\nIn my case `/home/amol/arrow/arrow/python/pyarrow/lib.pyx` VS `/home/amol/arrow/arrow/python/pyarrow/array.pxi`\r\n\r\n**Expected behavior**\r\n`cy list` uses the file where the function was declared into\r\n\r\n**Environment (please complete the following information):**\r\n - OS: Linux\r\n - Python version 3.9.4\r\n - Cython version 3.0a6\r\n - GDB version 9.1\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "With the propsed PR in place `cy list` seem to work correctly\r\n\r\n```\r\npyarrow/tests/test_array.py::test_to_numpy_zero_copy \r\nThread 1 \"python\" hit Breakpoint 1, __pyx_pf_7pyarrow_3lib_5Array_61to_numpy (__pyx_v_self=0x4310ab <function_code_fastcall+513>, __pyx_v_zero_copy_only=None, __pyx_v_writable=<unknown at remote 0x7ffff52d3440>) at /home/amol/arrow/arrow/python/build/temp.linux-x86_64-3.9-pydebug/lib.cpp:99930\r\n99930\tstatic PyObject *__pyx_pf_7pyarrow_3lib_5Array_61to_numpy(struct __pyx_obj_7pyarrow_3lib_Array *__pyx_v_self, PyObject *__pyx_v_zero_copy_only, PyObject *__pyx_v_writable) {\r\n1134        def to_numpy(self, zero_copy_only=True, writable=False):\r\n(gdb) cy list\r\n  1129            values = self.to_numpy(zero_copy_only=False)\r\n  1130            if dtype is None:\r\n  1131                return values\r\n  1132            return values.astype(dtype)\r\n  1133    \r\n> 1134        def to_numpy(self, zero_copy_only=True, writable=False):\r\n  1135            \"\"\"\r\n  1136            Return a NumPy view or copy of this array (experimental).\r\n  1137    \r\n  1138            By default, tries to return a view of this array. This is only\r\n```",
            "created_at": "2021-05-19T10:13:53Z",
            "html_url": "https://github.com/cython/cython/issues/4174#issuecomment-843957657",
            "id": 843957657,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4174",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg0Mzk1NzY1Nw==",
            "performed_via_github_app": null,
            "updated_at": "2021-05-19T10:13:53Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/843957657",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/601423?v=4",
                "events_url": "https://api.github.com/users/amol-/events{/privacy}",
                "followers_url": "https://api.github.com/users/amol-/followers",
                "following_url": "https://api.github.com/users/amol-/following{/other_user}",
                "gists_url": "https://api.github.com/users/amol-/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/amol-",
                "id": 601423,
                "login": "amol-",
                "node_id": "MDQ6VXNlcjYwMTQyMw==",
                "organizations_url": "https://api.github.com/users/amol-/orgs",
                "received_events_url": "https://api.github.com/users/amol-/received_events",
                "repos_url": "https://api.github.com/users/amol-/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/amol-/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/amol-/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/amol-"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4174/comments",
    "created_at": "2021-05-19T10:08:30Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-05-24T10:27:50Z",
            "event": "milestoned",
            "id": 4785944132,
            "milestone": {
                "title": "3.0"
            },
            "node_id": "MDE1Ok1pbGVzdG9uZWRFdmVudDQ3ODU5NDQxMzI=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/4785944132"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-05-24T10:27:59Z",
            "event": "labeled",
            "id": 4785944765,
            "label": {
                "color": "444444",
                "name": "Debugger"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDQ3ODU5NDQ3NjU=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/4785944765"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-05-24T10:27:59Z",
            "event": "labeled",
            "id": 4785944768,
            "label": {
                "color": "444444",
                "name": "defect"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDQ3ODU5NDQ3Njg=",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/4785944768"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4174/events",
    "html_url": "https://github.com/cython/cython/issues/4174",
    "id": 895250931,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425567215,
            "name": "Debugger",
            "node_id": "MDU6TGFiZWw0MjU1NjcyMTU=",
            "url": "https://api.github.com/repos/cython/cython/labels/Debugger"
        },
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425553654,
            "name": "defect",
            "node_id": "MDU6TGFiZWw0MjU1NTM2NTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/defect"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4174/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 380,
        "created_at": "2018-08-18T06:33:08Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
            "events_url": "https://api.github.com/users/scoder/events{/privacy}",
            "followers_url": "https://api.github.com/users/scoder/followers",
            "following_url": "https://api.github.com/users/scoder/following{/other_user}",
            "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/scoder",
            "id": 491659,
            "login": "scoder",
            "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
            "organizations_url": "https://api.github.com/users/scoder/orgs",
            "received_events_url": "https://api.github.com/users/scoder/received_events",
            "repos_url": "https://api.github.com/users/scoder/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/scoder"
        },
        "description": "Goals:\r\n– New version scheme: 3.x instead of 0.x.\r\n– Change default `language_level` from `2` to `3`.\r\n– Change default for `binding` directive from `False` to `True`.\r\n– Fix some Python compatibility issues (if possible, allowing for breaking changes).\r\n",
        "due_on": null,
        "html_url": "https://github.com/cython/cython/milestone/58",
        "id": 3580387,
        "labels_url": "https://api.github.com/repos/cython/cython/milestones/58/labels",
        "node_id": "MDk6TWlsZXN0b25lMzU4MDM4Nw==",
        "number": 58,
        "open_issues": 27,
        "state": "open",
        "title": "3.0",
        "updated_at": "2021-05-24T13:57:52Z",
        "url": "https://api.github.com/repos/cython/cython/milestones/58"
    },
    "node_id": "MDU6SXNzdWU4OTUyNTA5MzE=",
    "number": 4174,
    "performed_via_github_app": null,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "[BUG] CyGDB doesn't deal properly with .pxi files.",
    "updated_at": "2021-05-24T10:27:59Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4174",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/601423?v=4",
        "events_url": "https://api.github.com/users/amol-/events{/privacy}",
        "followers_url": "https://api.github.com/users/amol-/followers",
        "following_url": "https://api.github.com/users/amol-/following{/other_user}",
        "gists_url": "https://api.github.com/users/amol-/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/amol-",
        "id": 601423,
        "login": "amol-",
        "node_id": "MDQ6VXNlcjYwMTQyMw==",
        "organizations_url": "https://api.github.com/users/amol-/orgs",
        "received_events_url": "https://api.github.com/users/amol-/received_events",
        "repos_url": "https://api.github.com/users/amol-/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/amol-/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/amol-/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/amol-"
    }
}