{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I'm trying to install `pyzmq` on Debian bullseye using CPython 3.10. Although the error arises during the build of zmq, I feel like the root cause is actually Cython generated code that no longer conforms to the CPython API. \r\n\r\nI have removed all my pins for pyzmq so I plan to install `Cython==0.29.24` & `pyzmq==22.3.0`\r\n\r\n```#12 31.35     zmq/backend/cython/_device.c: In function ‘__Pyx__ExceptionSave’:\r\n#12 31.35     zmq/backend/cython/_device.c:3120:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?\r\n#12 31.35      3120 |     *type = tstate->exc_type;\r\n#12 31.35           |                     ^~~~~~~~\r\n#12 31.35           |                     curexc_type\r\n#12 31.36     zmq/backend/cython/_device.c:3121:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?\r\n#12 31.36      3121 |     *value = tstate->exc_value;\r\n#12 31.36           |                      ^~~~~~~~~\r\n#12 31.36           |                      curexc_value\r\n#12 31.36     zmq/backend/cython/_device.c:3122:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?\r\n#12 31.36      3122 |     *tb = tstate->exc_traceback;\r\n#12 31.36           |                   ^~~~~~~~~~~~~\r\n#12 31.36           |                   curexc_traceback\r\n#12 31.36     zmq/backend/cython/_device.c: In function ‘__Pyx__ExceptionReset’:\r\n#12 31.36     zmq/backend/cython/_device.c:3129:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?\r\n#12 31.36      3129 |     tmp_type = tstate->exc_type;\r\n#12 31.36           |                        ^~~~~~~~\r\n#12 31.36           |                        curexc_type\r\n#12 31.36     zmq/backend/cython/_device.c:3130:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?\r\n#12 31.36      3130 |     tmp_value = tstate->exc_value;\r\n#12 31.36           |                         ^~~~~~~~~\r\n#12 31.36           |                         curexc_value\r\n#12 31.36     zmq/backend/cython/_device.c:3131:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?\r\n#12 31.36      3131 |     tmp_tb = tstate->exc_traceback;\r\n#12 31.36           |                      ^~~~~~~~~~~~~\r\n#12 31.36           |                      curexc_traceback\r\n#12 31.36     zmq/backend/cython/_device.c:3132:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?\r\n#12 31.36      3132 |     tstate->exc_type = type;\r\n#12 31.36           |             ^~~~~~~~\r\n#12 31.36           |             curexc_type\r\n#12 31.36     zmq/backend/cython/_device.c:3133:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?\r\n#12 31.36      3133 |     tstate->exc_value = value;\r\n#12 31.36           |             ^~~~~~~~~\r\n#12 31.36           |             curexc_value\r\n#12 31.36     zmq/backend/cython/_device.c:3134:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?\r\n#12 31.36      3134 |     tstate->exc_traceback = tb;\r\n#12 31.36           |             ^~~~~~~~~~~~~\r\n#12 31.36           |             curexc_traceback\r\n#12 31.36     zmq/backend/cython/_device.c: In function ‘__Pyx__GetException’:\r\n#12 31.36     zmq/backend/cython/_device.c:3189:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?\r\n#12 31.36      3189 |     tmp_type = tstate->exc_type;\r\n#12 31.36           |                        ^~~~~~~~\r\n#12 31.36           |                        curexc_type\r\n#12 31.36     zmq/backend/cython/_device.c:3190:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?\r\n#12 31.36      3190 |     tmp_value = tstate->exc_value;\r\n#12 31.36           |                         ^~~~~~~~~\r\n#12 31.36           |                         curexc_value\r\n#12 31.36     zmq/backend/cython/_device.c:3191:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?\r\n#12 31.36      3191 |     tmp_tb = tstate->exc_traceback;\r\n#12 31.36           |                      ^~~~~~~~~~~~~\r\n#12 31.36           |                      curexc_traceback\r\n#12 31.36     zmq/backend/cython/_device.c:3192:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?\r\n#12 31.36      3192 |     tstate->exc_type = local_type;\r\n#12 31.36           |             ^~~~~~~~\r\n#12 31.36           |             curexc_type\r\n#12 31.36     zmq/backend/cython/_device.c:3193:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?\r\n#12 31.36      3193 |     tstate->exc_value = local_value;\r\n#12 31.36           |             ^~~~~~~~~\r\n#12 31.36           |             curexc_value\r\n#12 31.36     zmq/backend/cython/_device.c:3194:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?\r\n#12 31.36      3194 |     tstate->exc_traceback = local_tb;\r\n#12 31.36           |             ^~~~~~~~~~~~~\r\n#12 31.36           |             curexc_traceback\r\n#12 31.39     error: command '/usr/bin/gcc' failed with exit code 1\r\n#12 31.42     Running setup.py install for pyzmq: finished with status 'error'\r\n#12 31.42   Rolling back uninstall of pyzmq\r\n#12 31.42   Moving to /usr/local/lib/python3.10/site-packages/pyzmq-22.3.0.dist-info/\r\n#12 31.42    from /usr/local/lib/python3.10/site-packages/~yzmq-22.3.0.dist-info\r\n#12 31.42   Moving to /usr/local/lib/python3.10/site-packages/zmq/\r\n#12 31.42    from /usr/local/lib/python3.10/site-packages/~mq\r\n#12 31.42 ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-x5ovr3m7/pyzmq_5cd7f6a5ed1549d89d0af7f4ae5a5e5f/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-x5ovr3m7/pyzmq_5cd7f6a5ed1549d89d0af7f4ae5a5e5f/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-qjly6k5y/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/pyzmq Check the logs for full command output.```\r\n\r\nI'm happy to provide anymore supporting information.",
    "closed_at": "2021-10-18T19:04:07Z",
    "comment_data": [
        {
            "author_association": "COLLABORATOR",
            "body": "I think this has been fixed for a good while https://github.com/cython/cython/issues/1955 (and you can find other similar issues as well).\r\n\r\nWhat will be happening is that pyzmq will be providing .c files built with an older version of Cython. Your options are to force the .c files to be regenerated with a newer version of Cython (how you do this depends on their build system so I don't think we can answer that) or ask their maintainers to do this (probably a good idea anyway)",
            "created_at": "2021-10-18T19:04:07Z",
            "html_url": "https://github.com/cython/cython/issues/4421#issuecomment-946076006",
            "id": 946076006,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4421",
            "node_id": "IC_kwDOABDGAc44Y_lm",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/946076006/reactions"
            },
            "updated_at": "2021-10-18T19:04:07Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/946076006",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "COLLABORATOR",
            "body": "Hmmm... It doesn't look like ZMQ bundles any C files. I still think it's an \"old version of Cython\" problem. I'd check very carefully what you have installed, and look at the top of the .c files - it should say something like \"generated with Cython 0.xx.xx\"",
            "created_at": "2021-10-18T19:08:09Z",
            "html_url": "https://github.com/cython/cython/issues/4421#issuecomment-946079240",
            "id": 946079240,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4421",
            "node_id": "IC_kwDOABDGAc44ZAYI",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/946079240/reactions"
            },
            "updated_at": "2021-10-18T19:08:09Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/946079240",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4421/comments",
    "created_at": "2021-10-18T18:49:43Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-10-18T19:04:07Z",
            "event": "closed",
            "id": 5480622732,
            "node_id": "CE_lADOABDGAc49XIUjzwAAAAFGq6qM",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/5480622732"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-10-18T19:04:32Z",
            "event": "labeled",
            "id": 5480625801,
            "label": {
                "color": "000000",
                "name": "R: third party"
            },
            "node_id": "LE_lADOABDGAc49XIUjzwAAAAFGq7aJ",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/5480625801"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2021-10-18T19:04:32Z",
            "event": "labeled",
            "id": 5480625806,
            "label": {
                "color": "fef2c0",
                "name": "support question"
            },
            "node_id": "LE_lADOABDGAc49XIUjzwAAAAFGq7aO",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/5480625806"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4421/events",
    "html_url": "https://github.com/cython/cython/issues/4421",
    "id": 1029473571,
    "labels": [
        {
            "color": "fef2c0",
            "default": false,
            "description": null,
            "id": 414800623,
            "name": "support question",
            "node_id": "MDU6TGFiZWw0MTQ4MDA2MjM=",
            "url": "https://api.github.com/repos/cython/cython/labels/support%20question"
        },
        {
            "color": "000000",
            "default": false,
            "description": "",
            "id": 1840758668,
            "name": "R: third party",
            "node_id": "MDU6TGFiZWwxODQwNzU4NjY4",
            "url": "https://api.github.com/repos/cython/cython/labels/R:%20third%20party"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4421/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc49XIUj",
    "number": 4421,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/4421/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/4421/timeline",
    "title": "Cannot Install ZMQ Cython backend on Python3.10 Debian bullseye ",
    "updated_at": "2021-10-18T19:08:09Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4421",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/3302930?v=4",
        "events_url": "https://api.github.com/users/rtilk89/events{/privacy}",
        "followers_url": "https://api.github.com/users/rtilk89/followers",
        "following_url": "https://api.github.com/users/rtilk89/following{/other_user}",
        "gists_url": "https://api.github.com/users/rtilk89/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/rtilk89",
        "id": 3302930,
        "login": "rtilk89",
        "node_id": "MDQ6VXNlcjMzMDI5MzA=",
        "organizations_url": "https://api.github.com/users/rtilk89/orgs",
        "received_events_url": "https://api.github.com/users/rtilk89/received_events",
        "repos_url": "https://api.github.com/users/rtilk89/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/rtilk89/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rtilk89/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/rtilk89"
    }
}