{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Cython compiler forgets to generate declaration for tuple type in cpp vector.  For example, if you use type like `vector[(int, int)]`, it is possible that Cython forget to generate declaration for type `(int, int)` in cpp source file.\r\n\r\n**To Reproduce**\r\n```cython\r\n# cython: language_level=3\r\n# distutils: language = c++\r\n\r\nimport cython\r\nfrom libcpp.vector cimport vector \r\n\r\ndef f(n):\r\n    cdef vector[(int, int)] v\r\n    for _ in range(n):\r\n        v.push_back((1, 2))\r\n    print(v)\r\n    return\r\n```\r\nCompile it, and you will get a quite long error info. In brief, gcc complains that type `(int, int)` is not declared.\r\n```\r\nxxxx.cpp:1207:65: error: ‘__pyx_ctuple_int__and_int’ was not declared in this scope\r\n```\r\n\r\n## Workaround\r\nAs a workaround, you may add one line like \r\n```cython\r\nctypedef (int, int) tuple_int_int\r\n```\r\nwhich forces cython to generate declaration for type `(int, int)` in cpp source file, and gcc does not complain any more.",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "The workaround works also with pure python sintax, putting outside the function\r\n\r\n`tuple_int_int = cython.typedef((cython.int, cython.int))`\r\n\r\nthank you!",
            "created_at": "2022-11-13T13:18:19Z",
            "html_url": "https://github.com/cython/cython/issues/4835#issuecomment-1312728853",
            "id": 1312728853,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4835",
            "node_id": "IC_kwDOABDGAc5OPqcV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1312728853/reactions"
            },
            "updated_at": "2022-11-13T13:18:38Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1312728853",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/68152031?v=4",
                "events_url": "https://api.github.com/users/Tortar/events{/privacy}",
                "followers_url": "https://api.github.com/users/Tortar/followers",
                "following_url": "https://api.github.com/users/Tortar/following{/other_user}",
                "gists_url": "https://api.github.com/users/Tortar/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Tortar",
                "id": 68152031,
                "login": "Tortar",
                "node_id": "MDQ6VXNlcjY4MTUyMDMx",
                "organizations_url": "https://api.github.com/users/Tortar/orgs",
                "received_events_url": "https://api.github.com/users/Tortar/received_events",
                "repos_url": "https://api.github.com/users/Tortar/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Tortar/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Tortar/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Tortar"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4835/comments",
    "created_at": "2022-06-12T19:46:00Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4835/events",
    "html_url": "https://github.com/cython/cython/issues/4835",
    "id": 1268681965,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4835/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5Lnozt",
    "number": 4835,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 1,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/cython/cython/issues/4835/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/4835/timeline",
    "title": "[BUG] tuple type in vector is not properly declared in cpp source. ",
    "updated_at": "2022-11-16T11:59:32Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4835",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/8087906?v=4",
        "events_url": "https://api.github.com/users/liqimai/events{/privacy}",
        "followers_url": "https://api.github.com/users/liqimai/followers",
        "following_url": "https://api.github.com/users/liqimai/following{/other_user}",
        "gists_url": "https://api.github.com/users/liqimai/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/liqimai",
        "id": 8087906,
        "login": "liqimai",
        "node_id": "MDQ6VXNlcjgwODc5MDY=",
        "organizations_url": "https://api.github.com/users/liqimai/orgs",
        "received_events_url": "https://api.github.com/users/liqimai/received_events",
        "repos_url": "https://api.github.com/users/liqimai/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/liqimai/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/liqimai/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/liqimai"
    }
}