{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\n\nIt seems like the profiling function will cause CPython to crash with Cython compiled modules. I have reproduced this issue with spaCy, but according to their devs(https://github.com/explosion/spaCy/issues/12105) it would reproduce on any Cython modules.\r\n\r\nThis will only happen on Python 3.11, which changed the layout of frames significantly. It was originally found in viztracer(https://github.com/gaogaotiantian/viztracer/issues/307).\n\n### Code to reproduce the behaviour:\n\n```python\r\nimport sys\r\ndef func(*args):\r\n    frame = args[0]\r\n    while frame:\r\n        frame = frame.f_back\r\n\r\nsys.setprofile(func)\r\nimport spacy\r\n```\r\n\r\n\r\nThe segfault happens at `<frame at 0x7f2c80f1fa30, file 'thinc/backends/numpy_ops.pyx', line 1, code __Pyx_PyMODINIT_FUNC PyInit_numpy_ops(void)>`.\n\n### Expected behaviour\n\nNo segfault.\n\n### Environment\n\nOS: [Linux]\r\nPython version [3.11]\r\nCython version [Not sure what they used to compile the module]\r\nspaCy version [3.4.4]\n\n### Additional context\n\n_No response_",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5222/comments",
    "created_at": "2023-01-20T17:22:19Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5222/events",
    "html_url": "https://github.com/cython/cython/issues/5222",
    "id": 1551206338,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5222/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5cdYfC",
    "number": 5222,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5222/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5222/timeline",
    "title": "[BUG] Segfault when profiling a module compiled by Cython on 3.11",
    "updated_at": "2023-01-20T17:22:19Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5222",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/13121107?v=4",
        "events_url": "https://api.github.com/users/gaogaotiantian/events{/privacy}",
        "followers_url": "https://api.github.com/users/gaogaotiantian/followers",
        "following_url": "https://api.github.com/users/gaogaotiantian/following{/other_user}",
        "gists_url": "https://api.github.com/users/gaogaotiantian/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/gaogaotiantian",
        "id": 13121107,
        "login": "gaogaotiantian",
        "node_id": "MDQ6VXNlcjEzMTIxMTA3",
        "organizations_url": "https://api.github.com/users/gaogaotiantian/orgs",
        "received_events_url": "https://api.github.com/users/gaogaotiantian/received_events",
        "repos_url": "https://api.github.com/users/gaogaotiantian/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/gaogaotiantian/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gaogaotiantian/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/gaogaotiantian"
    }
}