{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\n\nWhen `make_unique` was provided in `memory.pxd` in https://github.com/cython/cython/pull/487, it didn't come with an `except +` annotation. At the time, this was due to the Cython compiler not emitting the correct `std::move(...)` in the subsequent assignment in the transpiled source code.\r\n\r\nAFAICT this can be worked around in a reasonable manner by explicitly putting a `move` call in the rvalue of the assignment, and although that is less ergonomic, perhaps it is better because exceptions will actually be caught.\r\nIn the intervening years, it looks like this restriction has gone, and so `except +` should be reintroduced. The issue here is that a (potentially) throwing constructor wrapped by `make_unique` does not \n\n### Code to reproduce the behaviour:\n\n```cython\r\nfrom libcpp.utility cimport move\r\nfrom libcpp.memory cimport unique_ptr\r\nfrom libcpp.vector cimport vector\r\n\r\ndef some_function(int n):\r\n    cdef unique_ptr[vector[double]] vec\r\n\r\n    with nogil:\r\n        vec = move(make_unique[vector[double]](n))\r\n\r\n    return vec.get().size()\r\n```\r\n\n\n### Expected behaviour\n\nI expect this to be transpiled to:\r\n```c++\r\n        /* \"cython_except.pyx\":9\r\n * \r\n *     with nogil:\r\n *         vec = move(make_unique[vector[double]](n))             # <<<<<<<<<<<<<<\r\n * \r\n *     return vec.get().size()\r\n */\r\n        try {\r\n          __pyx_t_1 = std::make_unique<std::vector<double> >(__pyx_v_n);\r\n        } catch(...) {\r\n          #ifdef WITH_THREAD\r\n          PyGILState_STATE __pyx_gilstate_save = __Pyx_PyGILState_Ensure();\r\n          #endif\r\n          __Pyx_CppExn2PyErr();\r\n          #ifdef WITH_THREAD\r\n          __Pyx_PyGILState_Release(__pyx_gilstate_save);\r\n          #endif\r\n          __PYX_ERR(0, 9, __pyx_L4_error)\r\n        }\r\n        __pyx_v_vec = cython_std::move<std::unique_ptr<std::vector<double> > >(__PYX_STD_MOVE_IF_SUPPORTED(__pyx_t_1));\r\n      }\r\n```\r\n\r\nWhereas in fact it is transpiled to:\r\n```c++\r\n      /*try:*/ {\r\n\r\n        /* \"cython_except.pyx\":9\r\n * \r\n *     with nogil:\r\n *         vec = move(make_unique[vector[double]](n))             # <<<<<<<<<<<<<<\r\n * \r\n *     return vec.get().size()\r\n */\r\n        __pyx_v_vec = cython_std::move<std::unique_ptr<std::vector<double> > >(std::make_unique<std::vector<double> >(__pyx_v_n));\r\n      }\r\n```\n\n### OS\n\n Linux\n\n### Python version\n\n3.10.6\n\n### Cython version\n\n3.0.0\n\n### Additional context\n\n_No response_",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Maybe I'm missing some detail of C++, but I believe the explicit call to `std::move` should be unnecessary and the generated code can be simpler:\r\n\r\n```\r\n// exception stuff as above\r\n__pyx_v_vec = __PYX_STD_MOVE_IF_SUPPORTED(__pyx_t_1);\r\n```\r\n\r\nIf that's the case there's basically no reason not to add `except+` to our definition since all existing code would continue to work. The only question is whether the code detecting move support is robust enough.",
            "created_at": "2023-07-25T17:46:01Z",
            "html_url": "https://github.com/cython/cython/issues/5560#issuecomment-1650277646",
            "id": 1650277646,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5560",
            "node_id": "IC_kwDOABDGAc5iXT0O",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1650277646/reactions"
            },
            "updated_at": "2023-07-25T17:46:01Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1650277646",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I think that is correct. From some quick local testing that does appear to work. I'm going to try rebuilding a few of my libraries with this change to verify that there are no surprises.",
            "created_at": "2023-07-26T00:20:49Z",
            "html_url": "https://github.com/cython/cython/issues/5560#issuecomment-1650738688",
            "id": 1650738688,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5560",
            "node_id": "IC_kwDOABDGAc5iZEYA",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1650738688/reactions"
            },
            "updated_at": "2023-07-26T00:20:49Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1650738688",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1538165?v=4",
                "events_url": "https://api.github.com/users/vyasr/events{/privacy}",
                "followers_url": "https://api.github.com/users/vyasr/followers",
                "following_url": "https://api.github.com/users/vyasr/following{/other_user}",
                "gists_url": "https://api.github.com/users/vyasr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vyasr",
                "id": 1538165,
                "login": "vyasr",
                "node_id": "MDQ6VXNlcjE1MzgxNjU=",
                "organizations_url": "https://api.github.com/users/vyasr/orgs",
                "received_events_url": "https://api.github.com/users/vyasr/received_events",
                "repos_url": "https://api.github.com/users/vyasr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vyasr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vyasr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vyasr"
            }
        },
        {
            "author_association": "NONE",
            "body": "> Maybe I'm missing some detail of C++, but I believe the explicit call to `std::move` should be unnecessary and the generated code can be simpler:\r\n> \r\n> ```\r\n> // exception stuff as above\r\n> __pyx_v_vec = __PYX_STD_MOVE_IF_SUPPORTED(__pyx_t_1);\r\n> ```\r\n> \r\n> If that's the case there's basically no reason not to add `except+` to our definition since all existing code would continue to work. The only question is whether the code detecting move support is robust enough.\r\n\r\nI was (also) testing with Cython < 3 which transpiles this example:\r\n```cython\r\nfrom libcpp.utility cimport move\r\nfrom libcpp.memory cimport unique_ptr\r\nfrom libcpp.vector cimport vector\r\n\r\ncdef extern from \"<memory>\" namespace \"std\" nogil:\r\n    unique_ptr[T] make_unique[T](...) except +\r\n\r\ndef some_function(int n):\r\n    cdef unique_ptr[vector[double]] vec\r\n\r\n    with nogil:\r\n        vec = make_unique[vector[double]](n)\r\n\r\n    return vec.get().size()\r\n```\r\nto\r\n```c++\r\n      /*try:*/ {\r\n\r\n        /* \"cython_except.pyx\":12\r\n * \r\n *     with nogil:\r\n *         vec = make_unique[vector[double]](n)             # <<<<<<<<<<<<<<\r\n * \r\n *     return vec.get().size()\r\n */\r\n        try {\r\n          __pyx_t_1 = std::make_unique<std::vector<double> >(__pyx_v_n);\r\n        } catch(...) {\r\n          #ifdef WITH_THREAD\r\n          PyGILState_STATE __pyx_gilstate_save = __Pyx_PyGILState_Ensure();\r\n          #endif\r\n          __Pyx_CppExn2PyErr();\r\n          #ifdef WITH_THREAD\r\n          __Pyx_PyGILState_Release(__pyx_gilstate_save);\r\n          #endif\r\n          __PYX_ERR(0, 12, __pyx_L4_error)\r\n        }\r\n        __pyx_v_vec = __pyx_t_1;\r\n      }\r\n```\r\n\r\nHowever, with cython 3 we get\r\n```c++\r\n      /*try:*/ {\r\n\r\n        /* \"cython_except.pyx\":12\r\n * \r\n *     with nogil:\r\n *         vec = make_unique[vector[double]](n)             # <<<<<<<<<<<<<<\r\n * \r\n *     return vec.get().size()\r\n */\r\n        try {\r\n          __pyx_t_1 = std::make_unique<std::vector<double> >(__pyx_v_n);\r\n        } catch(...) {\r\n          #ifdef WITH_THREAD\r\n          PyGILState_STATE __pyx_gilstate_save = __Pyx_PyGILState_Ensure();\r\n          #endif\r\n          __Pyx_CppExn2PyErr();\r\n          #ifdef WITH_THREAD\r\n          __Pyx_PyGILState_Release(__pyx_gilstate_save);\r\n          #endif\r\n          __PYX_ERR(0, 12, __pyx_L4_error)\r\n        }\r\n        __pyx_v_vec = __PYX_STD_MOVE_IF_SUPPORTED(__pyx_t_1);\r\n      }\r\n```\r\nSo I agree it looks like the explicit `move` should not be necessary. Though perhaps that also means one shouldn't backport to cython < 3 since existing code might break.",
            "created_at": "2023-07-26T08:19:01Z",
            "html_url": "https://github.com/cython/cython/issues/5560#issuecomment-1651206762",
            "id": 1651206762,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5560",
            "node_id": "IC_kwDOABDGAc5ia2pq",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1651206762/reactions"
            },
            "updated_at": "2023-07-26T08:28:57Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1651206762",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
                "events_url": "https://api.github.com/users/wence-/events{/privacy}",
                "followers_url": "https://api.github.com/users/wence-/followers",
                "following_url": "https://api.github.com/users/wence-/following{/other_user}",
                "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wence-",
                "id": 1126981,
                "login": "wence-",
                "node_id": "MDQ6VXNlcjExMjY5ODE=",
                "organizations_url": "https://api.github.com/users/wence-/orgs",
                "received_events_url": "https://api.github.com/users/wence-/received_events",
                "repos_url": "https://api.github.com/users/wence-/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wence-"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5560/comments",
    "created_at": "2023-07-25T14:15:47Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
                "events_url": "https://api.github.com/users/wence-/events{/privacy}",
                "followers_url": "https://api.github.com/users/wence-/followers",
                "following_url": "https://api.github.com/users/wence-/following{/other_user}",
                "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wence-",
                "id": 1126981,
                "login": "wence-",
                "node_id": "MDQ6VXNlcjExMjY5ODE=",
                "organizations_url": "https://api.github.com/users/wence-/orgs",
                "received_events_url": "https://api.github.com/users/wence-/received_events",
                "repos_url": "https://api.github.com/users/wence-/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wence-"
            },
            "commit_id": "111ce41b1cf45244a65417724bc90c2c68dbc3fd",
            "commit_url": "https://api.github.com/repos/wence-/cudf/commits/111ce41b1cf45244a65417724bc90c2c68dbc3fd",
            "created_at": "2023-07-25T14:19:50Z",
            "event": "referenced",
            "id": 9912511002,
            "node_id": "REFE_lADOABDGAc5sgczxzwAAAAJO1Ooa",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9912511002"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
                "events_url": "https://api.github.com/users/wence-/events{/privacy}",
                "followers_url": "https://api.github.com/users/wence-/followers",
                "following_url": "https://api.github.com/users/wence-/following{/other_user}",
                "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wence-",
                "id": 1126981,
                "login": "wence-",
                "node_id": "MDQ6VXNlcjExMjY5ODE=",
                "organizations_url": "https://api.github.com/users/wence-/orgs",
                "received_events_url": "https://api.github.com/users/wence-/received_events",
                "repos_url": "https://api.github.com/users/wence-/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wence-"
            },
            "commit_id": "58631f8f2449da8f34864763d333571e0c65fd8f",
            "commit_url": "https://api.github.com/repos/wence-/cudf/commits/58631f8f2449da8f34864763d333571e0c65fd8f",
            "created_at": "2023-07-25T16:31:01Z",
            "event": "referenced",
            "id": 9914073817,
            "node_id": "REFE_lADOABDGAc5sgczxzwAAAAJO7MLZ",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9914073817"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
                "events_url": "https://api.github.com/users/wence-/events{/privacy}",
                "followers_url": "https://api.github.com/users/wence-/followers",
                "following_url": "https://api.github.com/users/wence-/following{/other_user}",
                "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wence-",
                "id": 1126981,
                "login": "wence-",
                "node_id": "MDQ6VXNlcjExMjY5ODE=",
                "organizations_url": "https://api.github.com/users/wence-/orgs",
                "received_events_url": "https://api.github.com/users/wence-/received_events",
                "repos_url": "https://api.github.com/users/wence-/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wence-"
            },
            "commit_id": "758483dde433344543108f57f7da6b1a01d166ff",
            "commit_url": "https://api.github.com/repos/wence-/cudf/commits/758483dde433344543108f57f7da6b1a01d166ff",
            "created_at": "2023-07-26T08:10:27Z",
            "event": "referenced",
            "id": 9920631682,
            "node_id": "REFE_lADOABDGAc5sgczxzwAAAAJPUNOC",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9920631682"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
                "events_url": "https://api.github.com/users/wence-/events{/privacy}",
                "followers_url": "https://api.github.com/users/wence-/followers",
                "following_url": "https://api.github.com/users/wence-/following{/other_user}",
                "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wence-",
                "id": 1126981,
                "login": "wence-",
                "node_id": "MDQ6VXNlcjExMjY5ODE=",
                "organizations_url": "https://api.github.com/users/wence-/orgs",
                "received_events_url": "https://api.github.com/users/wence-/received_events",
                "repos_url": "https://api.github.com/users/wence-/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wence-"
            },
            "commit_id": "ab77c9fa6eb256e0339c3ae8e6460366611b2fa3",
            "commit_url": "https://api.github.com/repos/wence-/cudf/commits/ab77c9fa6eb256e0339c3ae8e6460366611b2fa3",
            "created_at": "2023-07-26T08:53:14Z",
            "event": "referenced",
            "id": 9921080025,
            "node_id": "REFE_lADOABDGAc5sgczxzwAAAAJPV6rZ",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9921080025"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/in/85914?v=4",
                "events_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/events{/privacy}",
                "followers_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/followers",
                "following_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/following{/other_user}",
                "gists_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/apps/rapids-bot",
                "id": 73299758,
                "login": "rapids-bot[bot]",
                "node_id": "MDM6Qm90NzMyOTk3NTg=",
                "organizations_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/orgs",
                "received_events_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/received_events",
                "repos_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/rapids-bot%5Bbot%5D/subscriptions",
                "type": "Bot",
                "url": "https://api.github.com/users/rapids-bot%5Bbot%5D"
            },
            "commit_id": "427f8792e04662afeccad3beaae593817c52079f",
            "commit_url": "https://api.github.com/repos/rapidsai/cudf/commits/427f8792e04662afeccad3beaae593817c52079f",
            "created_at": "2023-07-26T12:28:14Z",
            "event": "referenced",
            "id": 9923497956,
            "node_id": "REFE_lADOABDGAc5sgczxzwAAAAJPfI_k",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9923497956"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5560/events",
    "html_url": "https://github.com/cython/cython/issues/5560",
    "id": 1820445937,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5560/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5sgczx",
    "number": 5560,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 2,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 2,
        "url": "https://api.github.com/repos/cython/cython/issues/5560/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5560/timeline",
    "title": "[BUG] `make_unique` not annotated with `except +`",
    "updated_at": "2023-07-26T08:28:57Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5560",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1126981?v=4",
        "events_url": "https://api.github.com/users/wence-/events{/privacy}",
        "followers_url": "https://api.github.com/users/wence-/followers",
        "following_url": "https://api.github.com/users/wence-/following{/other_user}",
        "gists_url": "https://api.github.com/users/wence-/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/wence-",
        "id": 1126981,
        "login": "wence-",
        "node_id": "MDQ6VXNlcjExMjY5ODE=",
        "organizations_url": "https://api.github.com/users/wence-/orgs",
        "received_events_url": "https://api.github.com/users/wence-/received_events",
        "repos_url": "https://api.github.com/users/wence-/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/wence-/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/wence-/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/wence-"
    }
}